mode: parallel
containers:
  - address: http://192.168.31.233:5700
    username: admin
    password: admin
    cid: admin
    secret: admin
    weigth:  
    mode: parallel
    limit: 9999
AtTime: 5 #填写1-12之间的数  填错自负默认为10  10点容易出现高峰超时。
IsHelp: true  #填写true或者false  false
IsOldV4: false #填写true或者false  false是否新版或者旧版V4
Wskey: false # 填空默认禁用wskey转换 需要的填true
IsAddFriend: false #填写true或者false  false
Lim: #填写1-N 代表限制次数
Tyt: #填写1-N 代表推一推需要的互助值，默认为8
Later: 1 #延时防止黑IP自己设置 默认60 不怕黑的改为1即可 单位是秒
ApiToken: #短信接入token参数 自定义设置 不要泄露给其他人
theme:  /root/xdd-plus/theme/admin.html
static: ./static
master:   #设置xdd8080端口密码 自定义设置 不要泄露给其他人
database:  /root/xdd-plus/.xdd.db
qywx_key:
daily_push:
resident:
user_agent:
telegram_bot_token:
telegram_user_id:
TGURL: #填写TG代理地址参考https://www.kejiwanjia.com/server/5221.html#3worker
qquid:   #管理员qq号 
qqgid:   #群号
qbot_public_mode: true
default_priority:
no_ghproxy: true
daily_asset_push_cron:
repos:
  - git: https://github.com/shufflewzc/faker2.git
